### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by jmarceli** [jas-chen/thisless-react#5]
Did you try to use this (really promising) approach on some bigger projects than todo?

**Comment by jas-chen** [comment]
Hi @jmarceli,

This project is more like a concept, and it is not used for production projects.

To be honest, memory management could be a challenge since there are so many streams and subscriptions. Developers have to handle them carefully, don't forget to unsubscribe / dispose unused resources. And that's why I don't recommend to use it in production / huge project.

**Comment by jmarceli** [comment]
Thanks for the reply. I'm just starting a new project and I was looking for the new ways of implementing redux.
